apiVersion: autoscaling/v2  # Utilisez la version appropriée
kind: HorizontalPodAutoscaler
metadata:
  name: service-company
  namespace: microservices
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-company
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Pourcentage d'utilisation CPU
