apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-company
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-company
  template:
    metadata:
      labels:
        app: service-company
    spec:
      containers:
        - name: service-company
          image: paulzk/seminar-service-company:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_APPLICATION_NAME
              value: "service-company"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://service-config:8080"
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://service-config:8080"
          resources:
            requests:
              cpu: "20m"  # Ajustez selon vos besoins
              memory: "512Mi"  # Ajustez selon vos besoins
            limits:
              cpu: "50m"  # Ajustez selon vos besoins
              memory: "1Gi"  # Ajustez selon vos besoins
