apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: service-register  
  namespace: microservices  
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      app: service-register  
  template:  
    metadata:  
      labels:  
        app: service-register  
    spec:  
      containers:  
      - name: service-register  
        image: paulzk/seminar-service-register:latest   # Remplacez par l'image de votre service register  
        ports:  
        - containerPort: 8761 # Remplacez par le port utilisé par le service register
        env:  
        - name: SPRING_APPLICATION_NAME  
          value: "service-register"  
        - name: SPRING_CLOUD_CONFIG_URI  
          value: "http://service-config:8080"  
        - name: SPRING_CONFIG_IMPORT  
          value: "configserver:http://service-config:8080"   

---  
apiVersion: v1  
kind: Service  
metadata:  
  name: service-register  
  namespace: microservices  
spec:  
  ports:  
  - port: 8761
    targetPort: 8761  
    protocol: TCP  
  selector:  
    app: service-register  
  type: LoadBalancer